---
title: "HW3"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HW3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
library(devtools)
library(tidyverse)
library(bookdown)
library(ggplot2)
library(UWBiostat561)
```

## Question 1 

### Question 1A

### Question 1B

### Question 1C

### Question 1D

```{r}
set.seed(0)
simulation <- UWBiostat561::generate_partial_clique(
  n = 10,
  clique_fraction = 0.5,
  clique_edge_density = 0.9
)

simulation$adj_mat
```


## Question 2

### Question 2A

### Question 2B

### Question 2C

```{r}
set.seed(0)
simulation <- UWBiostat561::generate_partial_clique(
  n = 30,
  clique_fraction = 0.5,
  clique_edge_density = 0.9
)

adj_mat <- simulation$adj_mat

res <- UWBiostat561::compute_maximal_partial_clique(
  adj_mat = adj_mat,
  alpha = 0.9
)
res

system.time(UWBiostat561::compute_maximal_partial_clique(
  adj_mat = adj_mat,
  alpha = 0.9
))
```
```{r}

```

## Question 3

### Question 3A

### Question 3B

### Question 3C

### Question 3D

## Question 4

### Question 4A

### Question 4B

### Question 4C

### Question 4D

## Question 5

### Question 5A

### Question 5B
